### PR TITLE
Convert to SDK style project

### PR DESCRIPTION
**Pull request by nosami**
I wasn't able to build this project in VS2019. Thought I would modernise it slightly to an SDK style project which now seems to work great.

### CODE REVIEW

**Comment by AshleyF** [comment]
Awesome, thanks for doing that!

**Comment by Squareys** [comment]
I seem to be unable to load the project:

```
D:\GitHub\VimSpeak\VimSpeak.fsproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  D:\GitHub\VimSpeak\VimSpeak.fsproj
```

Maybe you could add some hints to the README as to which Microsoft .NET SDK to install and such?

**Comment by Squareys** [comment]
Solution was to install ".NET Core SDK" via Visual Studio installer (via "Change...") rather than through a manually downloaded installer.

**Comment by Squareys** [comment]
Was finally able to build it after getting errors like:

```
Assets file 'D:\GitHub\VimSpeak\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
```

Instead of trying to go through Visual Studio, I built through:

```
msbuild VimSpeak.sln -t:restore
msbuild VimSpeak.sln /p:Configuration=Release /p:Platform="Any CPU"
```

The executable is then in `VimSpeak\bin\Release\net472\VimSpeak.exe`

**Pull request merged**
